title: Qinqin Zha # your name (or website title) here
logo: "/images/qlinkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Nerd at heart, brave at minds 
  <br><br>
  Projects Review 
  <br><br>
  <a href="https://www.linkedin.com/in/qinqin-zha-a5327147/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
